// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myxy.NET;

namespace Myxy.NET.Migrations
{
    [DbContext(typeof(MyxyContext))]
    [Migration("20210716070243_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Myxy.NET.AzDOMetadata", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnalyzedFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiledIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quarter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AzDOMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
