// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myxy.NET.Data;

namespace Myxy.NET.Migrations
{
    [DbContext(typeof(MyxyNETContext))]
    [Migration("20210721074941_up")]
    partial class up
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Myxy.NET.AzDO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnalyzedBuildCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnalyzedFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiledIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Period")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AzDO");
                });

            modelBuilder.Entity("Myxy.NET.E2EOnLinux", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedBuildCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiledIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Period")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("E2EOnLinux");
                });

            modelBuilder.Entity("Myxy.NET.E2EOnMac", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedBuildCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiledIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Period")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("E2EOnMac");
                });

            modelBuilder.Entity("Myxy.NET.E2EOnWindows", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedBuildCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiledIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Period")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("E2EOnWindows");
                });
#pragma warning restore 612, 618
        }
    }
}
